name: Go CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Test
        run: go test ./...
      - name: Lint
        run: golint ./...
      - name: Vet
        run: go vet ./...
      - name: Coverage
        run: |
          go test -coverprofile=coverage.txt ./...
          bash <(curl -s https://raw.githubusercontent.com/jacobl/go-coverage-report/master/report.sh)
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        if: ${{ success() && steps.test.conclusion == 'success' && steps.lint.conclusion == 'success' && steps.vet.conclusion == 'success' && steps.coverage.conclusion == 'success' }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.run_number }}
          body: Automatic release created by GitHub Actions# This workflow will build a golang project
          run: |
            goreleaser release --snapshot